<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Asesor extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Asesor_model');
    } 

    /*
     * Listing of asesor
     */
    function index()
    {
        $data['asesor'] = $this->Asesor_model->get_all_asesor();
        
        $data['_view'] = 'asesor/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new asesor
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'estado_id' => $this->input->post('estado_id'),
				'asesor_nombre' => $this->input->post('asesor_nombre'),
				'asesor_apellido' => $this->input->post('asesor_apellido'),
				'asesor_ci' => $this->input->post('asesor_ci'),
				'asesor_telefono' => $this->input->post('asesor_telefono'),
				'asesor_celular' => $this->input->post('asesor_celular'),
				'asesor_latitud' => $this->input->post('asesor_latitud'),
				'asesor_longitud' => $this->input->post('asesor_longitud'),
				'asesor_foto' => $this->input->post('asesor_foto'),
				'asesor_fechanac' => $this->input->post('asesor_fechanac'),
				'asesor_profesion' => $this->input->post('asesor_profesion'),
				'asesor_espcialidad' => $this->input->post('asesor_espcialidad'),
            );
            
            $asesor_id = $this->Asesor_model->add_asesor($params);
            redirect('asesor/index');
        }
        else
        {
			$this->load->model('Estado_model');
			$data['all_estado'] = $this->Estado_model->get_all_estado();
            
            $data['_view'] = 'asesor/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a asesor
     */
    function edit($asesor_id)
    {   
        // check if the asesor exists before trying to edit it
        $data['asesor'] = $this->Asesor_model->get_asesor($asesor_id);
        
        if(isset($data['asesor']['asesor_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'estado_id' => $this->input->post('estado_id'),
					'asesor_nombre' => $this->input->post('asesor_nombre'),
					'asesor_apellido' => $this->input->post('asesor_apellido'),
					'asesor_ci' => $this->input->post('asesor_ci'),
					'asesor_telefono' => $this->input->post('asesor_telefono'),
					'asesor_celular' => $this->input->post('asesor_celular'),
					'asesor_latitud' => $this->input->post('asesor_latitud'),
					'asesor_longitud' => $this->input->post('asesor_longitud'),
					'asesor_foto' => $this->input->post('asesor_foto'),
					'asesor_fechanac' => $this->input->post('asesor_fechanac'),
					'asesor_profesion' => $this->input->post('asesor_profesion'),
					'asesor_espcialidad' => $this->input->post('asesor_espcialidad'),
                );

                $this->Asesor_model->update_asesor($asesor_id,$params);            
                redirect('asesor/index');
            }
            else
            {
				$this->load->model('Estado_model');
				$data['all_estado'] = $this->Estado_model->get_all_estado();

                $data['_view'] = 'asesor/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The asesor you are trying to edit does not exist.');
    }
}
