<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Asistencia extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Asistencia_model');
    } 

    /*
     * Listing of asistencia
     */
    function index()
    {
        $data['asistencia'] = $this->Asistencia_model->get_all_asistencia();
        
        $data['_view'] = 'asistencia/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new asistencia
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'reunion_id' => $this->input->post('reunion_id'),
				'aistencia_fecha' => $this->input->post('aistencia_fecha'),
				'aistencia_hora' => $this->input->post('aistencia_hora'),
				'aistencia_registro' => $this->input->post('aistencia_registro'),
				'asistencia_observacion' => $this->input->post('asistencia_observacion'),
            );
            
            $asistencia_id = $this->Asistencia_model->add_asistencia($params);
            redirect('asistencia/index');
        }
        else
        {
			$this->load->model('Reunion_model');
			$data['all_reunion'] = $this->Reunion_model->get_all_reunion();
            
            $data['_view'] = 'asistencia/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a asistencia
     */
    function edit($aistencia_id)
    {   
        // check if the asistencia exists before trying to edit it
        $data['asistencia'] = $this->Asistencia_model->get_asistencia($aistencia_id);
        
        if(isset($data['asistencia']['aistencia_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'reunion_id' => $this->input->post('reunion_id'),
					'aistencia_fecha' => $this->input->post('aistencia_fecha'),
					'aistencia_hora' => $this->input->post('aistencia_hora'),
					'aistencia_registro' => $this->input->post('aistencia_registro'),
					'asistencia_observacion' => $this->input->post('asistencia_observacion'),
                );

                $this->Asistencia_model->update_asistencia($aistencia_id,$params);            
                redirect('asistencia/index');
            }
            else
            {
				$this->load->model('Reunion_model');
				$data['all_reunion'] = $this->Reunion_model->get_all_reunion();

                $data['_view'] = 'asistencia/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The asistencia you are trying to edit does not exist.');
    } 

    /*
     * Deleting asistencia
     */
    function remove($aistencia_id)
    {
        $asistencia = $this->Asistencia_model->get_asistencia($aistencia_id);

        // check if the asistencia exists before trying to delete it
        if(isset($asistencia['aistencia_id']))
        {
            $this->Asistencia_model->delete_asistencia($aistencia_id);
            redirect('asistencia/index');
        }
        else
            show_error('The asistencia you are trying to delete does not exist.');
    }
    
}
