<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Cliente extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Cliente_model');
    } 

    /*
     * Listing of cliente
     */
    function index()
    {
        $data['cliente'] = $this->Cliente_model->get_all_cliente();
        
        $data['_view'] = 'cliente/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new cliente
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'estadocivil_id' => $this->input->post('estadocivil_id'),
				'estado_id' => $this->input->post('estado_id'),
				'categoria_id' => $this->input->post('categoria_id'),
				'asesor_id' => $this->input->post('asesor_id'),
				'cliente_extencionci' => $this->input->post('cliente_extencionci'),
				'cliente_nombre' => $this->input->post('cliente_nombre'),
				'cliente_apellido' => $this->input->post('cliente_apellido'),
				'cliente_ci' => $this->input->post('cliente_ci'),
				'cliente_codigo' => $this->input->post('cliente_codigo'),
				'cliente_telefono' => $this->input->post('cliente_telefono'),
				'cliente_celular' => $this->input->post('cliente_celular'),
				'cliente_direccion' => $this->input->post('cliente_direccion'),
				'cliente_latitud' => $this->input->post('cliente_latitud'),
				'cliente_longitud' => $this->input->post('cliente_longitud'),
				'cliente_referencia' => $this->input->post('cliente_referencia'),
				'cliente_foto' => $this->input->post('cliente_foto'),
				'cliente_email' => $this->input->post('cliente_email'),
				'cliente_fechanac' => $this->input->post('cliente_fechanac'),
				'cliente_nit' => $this->input->post('cliente_nit'),
				'cliente_razon' => $this->input->post('cliente_razon'),
            );
            
            $cliente_id = $this->Cliente_model->add_cliente($params);
            redirect('cliente/index');
        }
        else
        {
			$this->load->model('Estado_civil_model');
			$data['all_estado_civil'] = $this->Estado_civil_model->get_all_estado_civil();

			$this->load->model('Estado_model');
			$data['all_estado'] = $this->Estado_model->get_all_estado();

			$this->load->model('Categoria_model');
			$data['all_categoria'] = $this->Categoria_model->get_all_categoria();

			$this->load->model('Asesor_model');
			$data['all_asesor'] = $this->Asesor_model->get_all_asesor();
            
            $data['_view'] = 'cliente/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a cliente
     */
    function edit($cliente_id)
    {   
        // check if the cliente exists before trying to edit it
        $data['cliente'] = $this->Cliente_model->get_cliente($cliente_id);
        
        if(isset($data['cliente']['cliente_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'estadocivil_id' => $this->input->post('estadocivil_id'),
					'estado_id' => $this->input->post('estado_id'),
					'categoria_id' => $this->input->post('categoria_id'),
					'asesor_id' => $this->input->post('asesor_id'),
					'cliente_extencionci' => $this->input->post('cliente_extencionci'),
					'cliente_nombre' => $this->input->post('cliente_nombre'),
					'cliente_apellido' => $this->input->post('cliente_apellido'),
					'cliente_ci' => $this->input->post('cliente_ci'),
					'cliente_codigo' => $this->input->post('cliente_codigo'),
					'cliente_telefono' => $this->input->post('cliente_telefono'),
					'cliente_celular' => $this->input->post('cliente_celular'),
					'cliente_direccion' => $this->input->post('cliente_direccion'),
					'cliente_latitud' => $this->input->post('cliente_latitud'),
					'cliente_longitud' => $this->input->post('cliente_longitud'),
					'cliente_referencia' => $this->input->post('cliente_referencia'),
					'cliente_foto' => $this->input->post('cliente_foto'),
					'cliente_email' => $this->input->post('cliente_email'),
					'cliente_fechanac' => $this->input->post('cliente_fechanac'),
					'cliente_nit' => $this->input->post('cliente_nit'),
					'cliente_razon' => $this->input->post('cliente_razon'),
                );

                $this->Cliente_model->update_cliente($cliente_id,$params);            
                redirect('cliente/index');
            }
            else
            {
				$this->load->model('Estado_civil_model');
				$data['all_estado_civil'] = $this->Estado_civil_model->get_all_estado_civil();

				$this->load->model('Estado_model');
				$data['all_estado'] = $this->Estado_model->get_all_estado();

				$this->load->model('Categoria_model');
				$data['all_categoria'] = $this->Categoria_model->get_all_categoria();

				$this->load->model('Asesor_model');
				$data['all_asesor'] = $this->Asesor_model->get_all_asesor();

                $data['_view'] = 'cliente/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The cliente you are trying to edit does not exist.');
    }
}
