<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Credito extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Credito_model');
        $this->load->model('Cuota_model');
        $this->load->model('Cliente_model');
         $this->load->helper('numeros');
    } 

    /*
     * Listing of credito
     */
    function index()
    {   
        $usuario_id = 1;
        $data['usuario_id'] = $usuario_id;
        $data['credito'] = $this->Credito_model->get_all_credito();
        
        $data['_view'] = 'credito/index';
        $this->load->view('layouts/main',$data);
    }

    function individual()
    {   
        $usuario_id = 1;
        $data['usuario_id'] = $usuario_id;
        $data['credito'] = $this->Credito_model->get_todo_credito();
        $this->load->model('Tipo_credito_model');
        $data['all_tipo_credito'] = $this->Tipo_credito_model->get_all_tipo_credito();
        $this->load->model('Tipo_interes_model');
        $data['all_tipo_interes'] = $this->Tipo_interes_model->get_all_tipo_interes();
        $this->load->model('Tipo_garantia_model');
        $data['all_tipo_garantia'] = $this->Tipo_garantia_model->get_all_tipo_garantia();
        $data['_view'] = 'credito/individual';
        $this->load->view('layouts/main',$data);
    }

    function grupal()
    {   
        $usuario_id = 1;
        $data['usuario_id'] = $usuario_id;
        
        $this->load->model('Grupo_model');
        $data['grupo'] = $this->Grupo_model->get_grupo_para_desembolso();
        
        $data['credito'] = $this->Credito_model->get_todo_credito();
        $this->load->model('Tipo_credito_model');
        $data['all_tipo_credito'] = $this->Tipo_credito_model->get_all_tipo_credito();
        $this->load->model('Tipo_interes_model');
        $data['all_tipo_interes'] = $this->Tipo_interes_model->get_all_tipo_interes();
        $this->load->model('Tipo_garantia_model');
        $data['all_tipo_garantia'] = $this->Tipo_garantia_model->get_all_tipo_garantia();
        $data['_view'] = 'credito/grupal';
        $this->load->view('layouts/main',$data);
    }

    function creditos()
    {   
        
     if ($this->input->is_ajax_request())
        {
            $parametro = $this->input->post('parametro');
           
            $datos = $this->Credito_model->get_buscar_credito($parametro);
            
            echo json_encode($datos);
        }
        else
        {                 
            show_404();
        }
        
    }
    /*
     * Adding a new credito
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'estado_id' => $this->input->post('estado_id'),
				'grupo_id' => $this->input->post('grupo_id'),
				'garantia_id' => $this->input->post('garantia_id'),
				'usuario_id' => $this->input->post('usuario_id'),
				'tipocredito_id' => $this->input->post('tipocredito_id'),
				'cliente_id' => $this->input->post('cliente_id'),
				'credito_fechainicio' => $this->input->post('credito_fechainicio'),
				'credito_horainicio' => $this->input->post('credito_horainicio'),
				'credito_monto' => $this->input->post('credito_monto'),
				'credito_interes' => $this->input->post('credito_interes'),
				'credito_cuotas' => $this->input->post('credito_cuotas'),
				'credito_fechalimite' => $this->input->post('credito_fechalimite'),
            );
            
            $credito_id = $this->Credito_model->add_credito($params);
            redirect('credito/index');
        }
        else
        {
			$this->load->model('Estado_model');
			$data['all_estado'] = $this->Estado_model->get_all_estado();

			$this->load->model('Grupo_model');
			$data['all_grupo'] = $this->Grupo_model->get_all_grupo();

			$this->load->model('Garantia_model');
			$data['all_garantia'] = $this->Garantia_model->get_all_garantia();

			$this->load->model('Usuario_model');
			$data['all_usuario'] = $this->Usuario_model->get_all_usuario();

			$this->load->model('Tipo_credito_model');
			$data['all_tipo_credito'] = $this->Tipo_credito_model->get_all_tipo_credito();

			$this->load->model('Cliente_model');
			$data['all_cliente'] = $this->Cliente_model->get_all_cliente();
            
            $data['_view'] = 'credito/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    function buscarcliente()
    {
        
                if ($this->input->is_ajax_request()) {       
                    
                    $cliente_ci = $this->input->post('cliente_ci');                    
                    $datos = $this->Credito_model->buscar_cliente($cliente_ci);
                    echo json_encode($datos);                        

                }
                else
                {                 
                            show_404();
                }  
        
               
    }

    function garantia_aux()
    {
        
                if ($this->input->is_ajax_request()) {       
                    
                    $cantidad = $this->input->post('cantidad');                    
                    $descripcion = $this->input->post('descripcion');                    
                    $precio = $this->input->post('precio');                    
                    $usuario_id = $this->input->post('usuario_id');                    
                    $this->Credito_model->crear_garantiaaux($cantidad,$descripcion,$precio,$usuario_id);
                    $datos = $this->Credito_model->mostrar_garantias($usuario_id);
                    echo json_encode($datos);                        

                }
                else
                {                 
                            show_404();
                }  
        
               
    }
    function garantiacredito()
    {
    

         if ($this->input->is_ajax_request()) {  
        $usuario_id = $this->input->post('usuario_id');
        $datos = $this->Credito_model->mostrar_garantias($usuario_id);
     if(isset($datos)){
                        echo json_encode($datos);
                    }else echo json_encode(null);
    }
        else
        {                 
                    show_404();
        }          
     
    
    } 

    function finalizar()
    {
        $usuario_id = 1;
        $credito_fechainicio = date("Y-m-d");
        $credito_horainicio = date("H:i:s");
        $cliente_id = $this->input->post('cliente_id');
        $intervalo = $this->input->post('intervalo');
         $params = array(
                'estado_id' => 9,
                //'grupo_id' => $this->input->post('grupo_id'),
                'credito_cuotadia' => $this->input->post('cuota_parcial'),
                'credito_cuotainteres' => $this->input->post('cuota_interes'),
                'credito_cuotaintervalo' => $this->input->post('intervalo'),
                'usuario_id' => $usuario_id,
                'tipocredito_id' => $this->input->post('tipo_credito'),
                'cliente_id' => $cliente_id,
                'credito_fechainicio' => $credito_fechainicio,
                'credito_horainicio' => $credito_horainicio,
                'credito_monto' => $this->input->post('credito_monto'),
                'credito_saldo' => $this->input->post('credito_monto'),
                'credito_interes' => $this->input->post('credito_interes'),
                'credito_custodia' => $this->input->post('credito_custodia'),
                'credito_comision' => $this->input->post('credito_comision'),
                'credito_cuotas' => $this->input->post('credito_cuotas'),
                'credito_fechalimite' => $this->input->post('credito_fechalimite'),
                'credito_ultimopago' => $credito_fechainicio,
                'tipogarant_id' => $this->input->post('tipo_garantia'),
                'tipoint_id' => $this->input->post('tipo_interes'),
            );
            
            $credito_id = $this->Credito_model->add_credito($params);
            
             $cli = array(
                    
                    'cliente_nombre' => $this->input->post('cliente_nombre'),
                    'cliente_apellido' => $this->input->post('cliente_apellido'),
                    'cliente_telefono' => $this->input->post('cliente_telefono'),
                   
                );

                $this->Cliente_model->update_cliente($cliente_id,$cli);   
    $modo =  $this->input->post('modo');
    $cuotas =  $this->input->post('credito_cuotas');
    $fechalimite = $this->input->post('credito_fechalimite');
    $fechafin = new DateTime($fechalimite);
    $fechahoy = new DateTime();
    $credito_interes = $this->input->post('credito_interes');
    $credito_custodia = $this->input->post('credito_custodia');
    $credito_comision = $this->input->post('credito_comision');
            
    $sumainteres = $credito_interes + $credito_custodia + $credito_comision;

    $diff = $fechahoy->diff($fechafin);
    $diferencia = $diff->days;
    $diferenciatotal = $diferencia+1;
    $tipo_interes = $this->input->post('tipo_interes');
   
    //$patron = ($numcuota*0.5) + 0.5;
             //credito individual //
                    
                        
if ($tipo_interes==2) { //interes fijo//
                                                 
   
           if ($modo>=1) {

            /*$ptq="UPDATE credito set credito_formapago=1 WHERE credito_id=".$credito_id." ";
            $this->db->query($ptq);*/
            $cuota_capital = $this->input->post('cuota_parcial');
            $cuota_interes = $this->input->post('cuota_interes');
           
                for ($numero = 1; $numero <= $cuotas; $numero++) {
            
            $monto = $this->input->post('credito_monto');
            
            $mod_date = strtotime($credito_fechainicio." +".$numero*$intervalo." days");
             $params = array(
                'credito_id' => $credito_id,
                'usuario_id' => $usuario_id,
                'estado_id' => 9,
                'cuota_numero' => $numero,
                'cuota_capital' => $cuota_capital,
                'cuota_interes' => $cuota_interes,
                'cuota_descuento' => 0,
                'cuota_monto' => ($cuota_capital + $cuota_interes),
                'cuota_fechalimite' => date("Y-m-d",$mod_date),
                'cuota_montocancelado' => 0,
                //'cuota_saldocapital' => $this->input->post('cuota_saldocapital'),//falta
            );
            
            $cuota_id = $this->Cuota_model->add_cuota($params);
            
            
        }
                
              //fin //
                            
    }else{  //numero de cuotas//
        
        for ($numero = 1; $numero <= $cuotas; $numero++) {
            
            $monto = $this->input->post('credito_monto');
            
            $mod_date = strtotime($fechalimite."+ ".($numero - 1)." months");
             $params = array(
                'credito_id' => $credito_id,
                'usuario_id' => $usuario_id,
                'estado_id' => 9,
                'cuota_numero' => $numero,
                'cuota_capital' => ($monto/$cuotas),
                'cuota_interes' => $sumainteres,
                'cuota_descuento' => 0,
                'cuota_monto' => ($sumainteres / 100 * $monto) + ($monto/$cuotas),
                'cuota_fechalimite' => date("Y-m-d",$mod_date),
                'cuota_montocancelado' => 0,
                //'cuota_saldocapital' => $this->input->post('cuota_saldocapital'),//falta
            );
            
            $cuota_id = $this->Cuota_model->add_cuota($params);
            
        }

    }
} else { //interes sobre saldo//
     
        if ($modo>=1) {
       
                 $monto = $this->input->post('credito_monto');
        
        $cuota_total = $monto;
        $saldo_deudor = $cuota_total;
        $cuota_capital = $monto/$cuotas;
        /*$ptq="UPDATE credito set credito_formapago=1 WHERE credito_id=".$credito_id." ";
        $this->db->query($ptq);*/
       
        /*for ($numero = 1; $numero <= $cuotas; $numero++) {
           
            $mod_date = strtotime($fechalimite."+ ".($numero)." days");
            $variable = $saldo_deudor * ($sumainteres/100/$cuotas);        
             $params = array(
                'credito_id' => $credito_id,
                'usuario_id' => $usuario_id,
                'estado_id' => 9,
                'cuota_numero' => $numero,
                'cuota_capital' => ($monto/$cuotas),
                'cuota_interes' => $sumainteres/$cuotas,
                'cuota_descuento' => 0,
                'cuota_monto' => $variable + ($monto/$cuotas),
                'cuota_fechalimite' => date("Y-m-d",$mod_date),
                'cuota_montocancelado' => 0,
                //'cuota_saldocapital' => $this->input->post('cuota_saldocapital'),//falta
            );
            
            $cuota_id = $this->Cuota_model->add_cuota($params);
            $cuota_total = $saldo_deudor;
            $saldo_deudor = $cuota_total - $cuota_capital;
                   
        }*/

        

              //fin ///  
                            
   }else{  //numero de cuotas//
        $monto = $this->input->post('credito_monto');
        
        $cuota_total = $monto;
        $saldo_deudor = $cuota_total;
        $cuota_capital = $monto/$cuotas;
        for ($numero = 1; $numero <= $cuotas; $numero++) {
            
            $mod_date = strtotime($fechalimite."+ ".($numero - 1)." months");
            $variable = $saldo_deudor * ($sumainteres/100);        
             $params = array(
                'credito_id' => $credito_id,
                'usuario_id' => $usuario_id,
                'estado_id' => 9,
                'cuota_numero' => $numero,
                'cuota_capital' => ($monto/$cuotas),
                'cuota_interes' => $sumainteres,
                'cuota_descuento' => 0,
                'cuota_monto' => $variable + ($monto/$cuotas),
                'cuota_fechalimite' => date("Y-m-d",$mod_date),
                'cuota_montocancelado' => 0,
                //'cuota_saldocapital' => $this->input->post('cuota_saldocapital'),//falta
            );
            
            $cuota_id = $this->Cuota_model->add_cuota($params);
            $cuota_total = $saldo_deudor;
            $saldo_deudor = $cuota_total - $cuota_capital;
            
        }

    }
}   
    $vaciar_garantia = "INSERT INTO garantia 
   (estado_id,
   garantia_descripcion,
   garantia_cantidad,
   garantia_precio,
   garantia_total,
   credito_id
   
   )
   (SELECT 
   estado_id,
   garantia_descripcion,
   garantia_cantidad,
   garantia_precio,
   garantia_total,
   ".$credito_id."
   
   FROM 
   garantia_aux
   WHERE
   usuario_id=".$usuario_id.")";
   $this->db->query($vaciar_garantia);

   $eliminar_aux = "DELETE FROM garantia_aux WHERE usuario_id=".$usuario_id." ";
   $this->db->query($eliminar_aux);

    }
    /*
     * Editing a credito
     */
    function completo($credito_id)
    {   
        $data['credito_id'] = $credito_id;
        $data['credito'] = $this->Credito_model->get_este_credito($credito_id);
        $this->load->model('Garantia_model');
        $data['garantias'] = $this->Garantia_model->get_garantia_credito($credito_id);
        $data['empresa'] = $this->Credito_model->get_empresa(1);
        $data['_view'] = 'credito/completo';
        $this->load->view('layouts/main',$data);
    }

     function planpago($credito_id)
    {
        $data['credito'] = $this->Credito_model->get_este_credito($credito_id);
        $data['cuota'] = $this->Cuota_model->get_all_cuotas($credito_id);
        $data['empresa'] = $this->Credito_model->get_empresa(1);
        $data['_view'] = 'cuota/planpago';
        $this->load->view('layouts/main',$data);
    }

    function edit($credito_id)
    {   
        // check if the credito exists before trying to edit it
        $data['credito'] = $this->Credito_model->get_credito($credito_id);
        
        if(isset($data['credito']['credito_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'estado_id' => $this->input->post('estado_id'),
					'grupo_id' => $this->input->post('grupo_id'),
					'garantia_id' => $this->input->post('garantia_id'),
					'usuario_id' => $this->input->post('usuario_id'),
					'tipocredito_id' => $this->input->post('tipocredito_id'),
					'cliente_id' => $this->input->post('cliente_id'),
					'credito_fechainicio' => $this->input->post('credito_fechainicio'),
					'credito_horainicio' => $this->input->post('credito_horainicio'),
					'credito_monto' => $this->input->post('credito_monto'),
					'credito_interes' => $this->input->post('credito_interes'),
					'credito_cuotas' => $this->input->post('credito_cuotas'),
					'credito_fechalimite' => $this->input->post('credito_fechalimite'),
                );

                $this->Credito_model->update_credito($credito_id,$params);            
                redirect('credito/index');
            }
            else
            {
				$this->load->model('Estado_model');
				$data['all_estado'] = $this->Estado_model->get_all_estado();

				$this->load->model('Grupo_model');
				$data['all_grupo'] = $this->Grupo_model->get_all_grupo();

				$this->load->model('Garantia_model');
				$data['all_garantia'] = $this->Garantia_model->get_all_garantia();

				$this->load->model('Usuario_model');
				$data['all_usuario'] = $this->Usuario_model->get_all_usuario();

				$this->load->model('Tipo_credito_model');
				$data['all_tipo_credito'] = $this->Tipo_credito_model->get_all_tipo_credito();

				$this->load->model('Cliente_model');
				$data['all_cliente'] = $this->Cliente_model->get_all_cliente();

                $data['_view'] = 'credito/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The credito you are trying to edit does not exist.');
    }
    
    function integrantes_grupo($grupo_id)
    {   
        $data['credito_id'] = $credito_id;
        $data['credito'] = $this->Credito_model->get_este_credito($credito_id);
        $this->load->model('Garantia_model');
        $data['garantias'] = $this->Garantia_model->get_garantia_credito($credito_id);
        $data['empresa'] = $this->Credito_model->get_empresa(1);
        $data['_view'] = 'credito/completo';
        $this->load->view('layouts/main',$data);
    }
    
}
