<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Credito extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Credito_model');
    } 

    /*
     * Listing of credito
     */
    function index()
    {
        $data['credito'] = $this->Credito_model->get_all_credito();
        
        $data['_view'] = 'credito/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new credito
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'estado_id' => $this->input->post('estado_id'),
				'grupo_id' => $this->input->post('grupo_id'),
				'garantia_id' => $this->input->post('garantia_id'),
				'usuario_id' => $this->input->post('usuario_id'),
				'tipocredito_id' => $this->input->post('tipocredito_id'),
				'cliente_id' => $this->input->post('cliente_id'),
				'credito_fechainicio' => $this->input->post('credito_fechainicio'),
				'credito_horainicio' => $this->input->post('credito_horainicio'),
				'credito_monto' => $this->input->post('credito_monto'),
				'credito_interes' => $this->input->post('credito_interes'),
				'credito_cuotas' => $this->input->post('credito_cuotas'),
				'credito_fechalimite' => $this->input->post('credito_fechalimite'),
            );
            
            $credito_id = $this->Credito_model->add_credito($params);
            redirect('credito/index');
        }
        else
        {
			$this->load->model('Estado_model');
			$data['all_estado'] = $this->Estado_model->get_all_estado();

			$this->load->model('Grupo_model');
			$data['all_grupo'] = $this->Grupo_model->get_all_grupo();

			$this->load->model('Garantia_model');
			$data['all_garantia'] = $this->Garantia_model->get_all_garantia();

			$this->load->model('Usuario_model');
			$data['all_usuario'] = $this->Usuario_model->get_all_usuario();

			$this->load->model('Tipo_credito_model');
			$data['all_tipo_credito'] = $this->Tipo_credito_model->get_all_tipo_credito();

			$this->load->model('Cliente_model');
			$data['all_cliente'] = $this->Cliente_model->get_all_cliente();
            
            $data['_view'] = 'credito/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a credito
     */
    function edit($credito_id)
    {   
        // check if the credito exists before trying to edit it
        $data['credito'] = $this->Credito_model->get_credito($credito_id);
        
        if(isset($data['credito']['credito_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'estado_id' => $this->input->post('estado_id'),
					'grupo_id' => $this->input->post('grupo_id'),
					'garantia_id' => $this->input->post('garantia_id'),
					'usuario_id' => $this->input->post('usuario_id'),
					'tipocredito_id' => $this->input->post('tipocredito_id'),
					'cliente_id' => $this->input->post('cliente_id'),
					'credito_fechainicio' => $this->input->post('credito_fechainicio'),
					'credito_horainicio' => $this->input->post('credito_horainicio'),
					'credito_monto' => $this->input->post('credito_monto'),
					'credito_interes' => $this->input->post('credito_interes'),
					'credito_cuotas' => $this->input->post('credito_cuotas'),
					'credito_fechalimite' => $this->input->post('credito_fechalimite'),
                );

                $this->Credito_model->update_credito($credito_id,$params);            
                redirect('credito/index');
            }
            else
            {
				$this->load->model('Estado_model');
				$data['all_estado'] = $this->Estado_model->get_all_estado();

				$this->load->model('Grupo_model');
				$data['all_grupo'] = $this->Grupo_model->get_all_grupo();

				$this->load->model('Garantia_model');
				$data['all_garantia'] = $this->Garantia_model->get_all_garantia();

				$this->load->model('Usuario_model');
				$data['all_usuario'] = $this->Usuario_model->get_all_usuario();

				$this->load->model('Tipo_credito_model');
				$data['all_tipo_credito'] = $this->Tipo_credito_model->get_all_tipo_credito();

				$this->load->model('Cliente_model');
				$data['all_cliente'] = $this->Cliente_model->get_all_cliente();

                $data['_view'] = 'credito/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The credito you are trying to edit does not exist.');
    }
}
