<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Cuota extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Cuota_model');
        $this->load->model('Credito_model');
        $this->load->helper('numeros');
    } 

    /*
     * Listing of cuota
     */
    function index()
    {
        $data['cuota'] = $this->Cuota_model->get_all_cuota();
        
        $data['_view'] = 'cuota/index';
        $this->load->view('layouts/main',$data);
    }

    function individual($credito_id)
    {
        $data['credito'] = $this->Credito_model->get_este_credito($credito_id);
        $data['cuota'] = $this->Cuota_model->get_all_cuotas($credito_id);
        $data['_view'] = 'cuota/individual';
        $this->load->view('layouts/main',$data);
    }

     function sintiempo($credito_id)
    {
        $data['credito'] = $this->Credito_model->get_este_credito($credito_id);
        $data['cuota'] = $this->Cuota_model->get_all_cuotas($credito_id);
        $data['_view'] = 'cuota/sintiempo';
        $this->load->view('layouts/main',$data);
    }
     function diario($credito_id)
    {
        $data['credito'] = $this->Credito_model->get_este_credito($credito_id);
        $data['cuota'] = $this->Cuota_model->get_all_cuotas($credito_id);
        $data['_view'] = 'cuota/diario';
        $this->load->view('layouts/main',$data);
    }

    function creditocuota($credito_id)
     {
    
         if ($this->input->is_ajax_request()) {  
        $datos = $this->Cuota_model->get_all_cuotas($credito_id);
     if(isset($datos)){
                        echo json_encode($datos);
                    }else echo json_encode(null);
    }
        else
        {                 
                    show_404();
        }          
     
    
    } 
     
    function pagar($cuota_id)
    {
        $credito_id = $this->input->post('credito');
        $fecha = $this->input->post('cuota_fechapago');
        $pagado = $this->input->post('cuota_montocancelado');
        $interes = $this->input->post('credito_interes');
        $comison = $this->input->post('credito_comision');
        $custodio = $this->input->post('credito_custodia');
        $saldar = $this->input->post('saldo');
        $suma = $interes+$comison+$custodio;
        $cuota_capital = $this->input->post('cuota_capital');
        $params = array(
                    'estado_id' => 10,                    
                    'cuota_montocancelado' => $this->input->post('cuota_montocancelado'),
                    'cuota_fechapago' => $this->input->post('cuota_fechapago'),
                    'cuota_horapago' => $this->input->post('cuota_horapago'),
                    'cuota_saldocapital' => $this->input->post('cuota_saldocapital'),
                    'cuota_numrecibo' => $this->input->post('cuota_numrecibo'),
                    //'cuota_banco' => $this->input->post('cuota_banco'),
                    'cuota_glosa' => $this->input->post('cuota_glosa'),
                );

                $this->Cuota_model->update_cuota($cuota_id,$params);


                $credito = "UPDATE credito SET credito_saldo=credito_saldo-".$cuota_capital.", credito_ultimopago='".$fecha."' WHERE credito_id=".$credito_id." ";
                $this->db->query($credito); 

                $saldo = "SELECT credito_saldo as saldito FROM credito WHERE credito_id=".$credito_id." ";
              $saldito = $this->db->query($saldo)->row_array();
              if ($saldito['saldito']==0) {
                  $credito_estado = "UPDATE credito SET estado_id=10 WHERE credito_id=".$credito_id." ";
                $this->db->query($credito_estado);    
                  }         
                redirect('cuota/individual/'.$credito_id);  

    } 

    function interes()
    {
        $credito_id = $this->input->post('credito_id');
        $usuario_id = 1;
        $fecha = $this->input->post('cuota_fechapago');
        $interes = $this->input->post('credito_interes');
        $comison = $this->input->post('credito_comision');
        $custodio = $this->input->post('credito_custodia');
        $suma = $interes+$comison+$custodio;
        $params = array(
                'credito_id' => $credito_id,
                'usuario_id' => $usuario_id,
                'estado_id' => 10,
                'cuota_numero' => 1,
                'cuota_capital' => 0,
                'cuota_interes' => $suma,
                'cuota_descuento' => 0,
                'cuota_monto' => $this->input->post('cuota_monto'),
                //'cuota_fechalimite' => $this->input->post('cuota_fechalimite'),
                'cuota_montocancelado' => $this->input->post('cuota_montocancelado'),
                'cuota_fechapago' => $this->input->post('cuota_fechapago'),
                'cuota_horapago' => $this->input->post('cuota_horapago'),
                'cuota_saldocapital' => $this->input->post('cuota_saldocapital'),
                'cuota_numrecibo' => $this->input->post('cuota_numrecibo'),
                //'cuota_banco' => $this->input->post('cuota_banco'),
                'cuota_glosa' => $this->input->post('cuota_glosa'),
            );
            
            $cuota_id = $this->Cuota_model->add_cuota($params);

                $credito = "UPDATE credito SET credito_ultimopago='".$fecha."' WHERE credito_id=".$credito_id." ";
                $this->db->query($credito);
                        
                redirect('cuota/sintiempo/'.$credito_id);  

    }    
    function amortizar()
    {
        $credito_id = $this->input->post('credito_id1');
        $usuario_id = 1;
        $interestotal = $this->input->post('interes1');
        $fecha = $this->input->post('cuota_fechapago1');
        $pagado = $this->input->post('cuota_montocancelado1');
        $interes = $this->input->post('credito_interes1');
        $comison = $this->input->post('credito_comision1');
        $custodio = $this->input->post('credito_custodia1');
        $suma = $interes+$comison+$custodio;
        $params = array(
                'credito_id' => $credito_id,
                'usuario_id' => $usuario_id,
                'estado_id' => 10,
                'cuota_numero' => 1,
                'cuota_capital' => $this->input->post('cuota_montocancelado1'),
                'cuota_interes' => $suma,
                'cuota_descuento' => 0,
                'cuota_monto' => $this->input->post('cuota_monto1'),
                //'cuota_fechalimite' => $this->input->post('cuota_fechalimite'),
                'cuota_montocancelado' => $this->input->post('cuota_montocancelado1'),
                'cuota_fechapago' => $this->input->post('cuota_fechapago1'),
                'cuota_horapago' => $this->input->post('cuota_horapago1'),
                'cuota_saldocapital' => $this->input->post('cuota_saldocapital1'),
                'cuota_numrecibo' => $this->input->post('cuota_numrecibo1'),
                //'cuota_banco' => $this->input->post('cuota_banco'),
                'cuota_glosa' => $this->input->post('cuota_glosa1'),
            );
            
            $cuota_id = $this->Cuota_model->add_cuota($params);


              $credito = "UPDATE credito SET credito_saldo=credito_saldo-".$pagado."+".$interestotal.", credito_ultimopago='".$fecha."' WHERE credito_id=".$credito_id." ";
                $this->db->query($credito);
              $saldo = "SELECT credito_saldo as saldito FROM credito WHERE credito_id=".$credito_id." ";
              $saldito = $this->db->query($saldo)->row_array();
              if ($saldito['saldito']==0) {
                  $credito_estado = "UPDATE credito SET estado_id=10 WHERE credito_id=".$credito_id." ";
                $this->db->query($credito_estado);    
                  }    
                redirect('cuota/sintiempo/'.$credito_id);  

    }

    function diariamente()
    {
        $credito_id = $this->input->post('credito_id');
        $usuario_id = 1;
        $dia = $this->input->post('dia');
        $fecha = $this->input->post('cuota_fechapago1');
        $pagado = $this->input->post('cuota_montocancelado');
        $interes = $this->input->post('credito_cuotainteres')*$dia;
        
        $params = array(
                'credito_id' => $credito_id,
                'usuario_id' => $usuario_id,
                'estado_id' => 10,
                'cuota_numero' => 1,
                'cuota_capital' => $this->input->post('credito_cuotadia')*$dia,
                'cuota_interes' => $this->input->post('credito_cuotainteres')*$dia,
                'cuota_descuento' => 0,
                'cuota_monto' => $this->input->post('cuota_monto'),
                //'cuota_fechalimite' => $this->input->post('cuota_fechalimite'),
                'cuota_montocancelado' => $this->input->post('cuota_montocancelado'),
                'cuota_fechapago' => $this->input->post('cuota_fechapago1'),
                'cuota_horapago' => $this->input->post('cuota_horapago1'),
                //'cuota_saldocapital' => $this->input->post('cuota_saldocapital1'),
                'cuota_numrecibo' => $this->input->post('cuota_numrecibo1'),
                //'cuota_banco' => $this->input->post('cuota_banco'),
                'cuota_glosa' => $this->input->post('cuota_glosa1'),
            );
            
            $cuota_id = $this->Cuota_model->add_cuota($params);


              $credito = "UPDATE credito SET credito_saldo=credito_saldo-".$pagado."+".$interes.", credito_ultimopago='".$fecha."' WHERE credito_id=".$credito_id." ";
                $this->db->query($credito);
              $saldo = "SELECT credito_saldo as saldito FROM credito WHERE credito_id=".$credito_id." ";
              $saldito = $this->db->query($saldo)->row_array();
              if ($saldito['saldito']==0) {
                  $credito_estado = "UPDATE credito SET estado_id=10 WHERE credito_id=".$credito_id." ";
                $this->db->query($credito_estado);    
                  }    
                redirect('cuota/diario/'.$credito_id);  

    }  

    function reciboindividual($credito_id,$cuota_id)
    {
        $data['credito'] = $this->Credito_model->get_este_credito($credito_id);
        $data['cuota'] = $this->Cuota_model->get_cuota($cuota_id);
       
        $data['_view'] = 'cuota/reciboindividual';
        $this->load->view('layouts/main',$data);
    }

    
    /*
     * Adding a new cuota
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'credito_id' => $this->input->post('credito_id'),
				'usuario_id' => $this->input->post('usuario_id'),
				'estado_id' => $this->input->post('estado_id'),
				'cuota_numero' => $this->input->post('cuota_numero'),
				'cuota_capital' => $this->input->post('cuota_capital'),
				'cuota_interes' => $this->input->post('cuota_interes'),
				'cuota_descuento' => $this->input->post('cuota_descuento'),
				'cuota_monto' => $this->input->post('cuota_monto'),
				'cuota_fechalimite' => $this->input->post('cuota_fechalimite'),
				'cuota_montocancelado' => $this->input->post('cuota_montocancelado'),
				'cuota_fechapago' => $this->input->post('cuota_fechapago'),
				'cuota_horapago' => $this->input->post('cuota_horapago'),
				'cuota_saldocapital' => $this->input->post('cuota_saldocapital'),
				'cuota_numrecibo' => $this->input->post('cuota_numrecibo'),
				'cuota_banco' => $this->input->post('cuota_banco'),
				'cuota_glosa' => $this->input->post('cuota_glosa'),
            );
            
            $cuota_id = $this->Cuota_model->add_cuota($params);
            redirect('cuota/index');
        }
        else
        {
			$this->load->model('Credito_model');
			$data['all_credito'] = $this->Credito_model->get_all_credito();

			$this->load->model('Usuario_model');
			$data['all_usuario'] = $this->Usuario_model->get_all_usuario();

			$this->load->model('Estado_model');
			$data['all_estado'] = $this->Estado_model->get_all_estado();
            
            $data['_view'] = 'cuota/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a cuota
     */
    function edit($cuota_id)
    {   
        // check if the cuota exists before trying to edit it
        $data['cuota'] = $this->Cuota_model->get_cuota($cuota_id);
        
        if(isset($data['cuota']['cuota_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'credito_id' => $this->input->post('credito_id'),
					'usuario_id' => $this->input->post('usuario_id'),
					'estado_id' => $this->input->post('estado_id'),
					'cuota_numero' => $this->input->post('cuota_numero'),
					'cuota_capital' => $this->input->post('cuota_capital'),
					'cuota_interes' => $this->input->post('cuota_interes'),
					'cuota_descuento' => $this->input->post('cuota_descuento'),
					'cuota_monto' => $this->input->post('cuota_monto'),
					'cuota_fechalimite' => $this->input->post('cuota_fechalimite'),
					'cuota_montocancelado' => $this->input->post('cuota_montocancelado'),
					'cuota_fechapago' => $this->input->post('cuota_fechapago'),
					'cuota_horapago' => $this->input->post('cuota_horapago'),
					'cuota_saldocapital' => $this->input->post('cuota_saldocapital'),
					'cuota_numrecibo' => $this->input->post('cuota_numrecibo'),
					'cuota_banco' => $this->input->post('cuota_banco'),
					'cuota_glosa' => $this->input->post('cuota_glosa'),
                );

                $this->Cuota_model->update_cuota($cuota_id,$params);            
                redirect('cuota/index');
            }
            else
            {
				$this->load->model('Credito_model');
				$data['all_credito'] = $this->Credito_model->get_all_credito();

				$this->load->model('Usuario_model');
				$data['all_usuario'] = $this->Usuario_model->get_all_usuario();

				$this->load->model('Estado_model');
				$data['all_estado'] = $this->Estado_model->get_all_estado();

                $data['_view'] = 'cuota/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The cuota you are trying to edit does not exist.');
    }
}
