<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Extencion extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Extencion_model');
    } 

    /*
     * Listing of extencion
     */
    function index()
    {
        $data['extencion'] = $this->Extencion_model->get_all_extencion();
        
        $data['_view'] = 'extencion/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new extencion
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
            );
            
            $extencion_id = $this->Extencion_model->add_extencion($params);
            redirect('extencion/index');
        }
        else
        {            
            $data['_view'] = 'extencion/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a extencion
     */
    function edit($cliente_extencionci)
    {   
        // check if the extencion exists before trying to edit it
        $data['extencion'] = $this->Extencion_model->get_extencion($cliente_extencionci);
        
        if(isset($data['extencion']['cliente_extencionci']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
                );

                $this->Extencion_model->update_extencion($cliente_extencionci,$params);            
                redirect('extencion/index');
            }
            else
            {
                $data['_view'] = 'extencion/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The extencion you are trying to edit does not exist.');
    } 

    /*
     * Deleting extencion
     */
    function remove($cliente_extencionci)
    {
        $extencion = $this->Extencion_model->get_extencion($cliente_extencionci);

        // check if the extencion exists before trying to delete it
        if(isset($extencion['cliente_extencionci']))
        {
            $this->Extencion_model->delete_extencion($cliente_extencionci);
            redirect('extencion/index');
        }
        else
            show_error('The extencion you are trying to delete does not exist.');
    }
    
}
