<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Garantia extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Garantia_model');
    } 

    /*
     * Listing of garantia
     */
    function index()
    {
        $data['garantia'] = $this->Garantia_model->get_all_garantia();
        
        $data['_view'] = 'garantia/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new garantia
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'estado_id' => $this->input->post('estado_id'),
				'garantia_descripcion' => $this->input->post('garantia_descripcion'),
				'garantia_codigo' => $this->input->post('garantia_codigo'),
				'garantia_cantidad' => $this->input->post('garantia_cantidad'),
				'garantia_precio' => $this->input->post('garantia_precio'),
				'garantia_observacion' => $this->input->post('garantia_observacion'),
            );
            
            $garantia_id = $this->Garantia_model->add_garantia($params);
            redirect('garantia/index');
        }
        else
        {
			$this->load->model('Estado_model');
			$data['all_estado'] = $this->Estado_model->get_all_estado();
            
            $data['_view'] = 'garantia/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a garantia
     */
    function edit($garantia_id)
    {   
        // check if the garantia exists before trying to edit it
        $data['garantia'] = $this->Garantia_model->get_garantia($garantia_id);
        
        if(isset($data['garantia']['garantia_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'estado_id' => $this->input->post('estado_id'),
					'garantia_descripcion' => $this->input->post('garantia_descripcion'),
					'garantia_codigo' => $this->input->post('garantia_codigo'),
					'garantia_cantidad' => $this->input->post('garantia_cantidad'),
					'garantia_precio' => $this->input->post('garantia_precio'),
					'garantia_observacion' => $this->input->post('garantia_observacion'),
                );

                $this->Garantia_model->update_garantia($garantia_id,$params);            
                redirect('garantia/index');
            }
            else
            {
				$this->load->model('Estado_model');
				$data['all_estado'] = $this->Estado_model->get_all_estado();

                $data['_view'] = 'garantia/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The garantia you are trying to edit does not exist.');
    } 

    /*
     * Deleting garantia
     */
    function remove($garantia_id)
    {
        $garantia = $this->Garantia_model->get_garantia($garantia_id);

        // check if the garantia exists before trying to delete it
        if(isset($garantia['garantia_id']))
        {
            $this->Garantia_model->delete_garantia($garantia_id);
            redirect('garantia/index');
        }
        else
            show_error('The garantia you are trying to delete does not exist.');
    }
    
}
