<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Multa extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Multa_model');
    } 

    /*
     * Listing of multa
     */
    function index()
    {
        $data['multa'] = $this->Multa_model->get_all_multa();
        
        $data['_view'] = 'multa/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new multa
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'reunion_id' => $this->input->post('reunion_id'),
				'usuario_id' => $this->input->post('usuario_id'),
				'multa_monto' => $this->input->post('multa_monto'),
				'multa_fecha' => $this->input->post('multa_fecha'),
				'multa_hora' => $this->input->post('multa_hora'),
				'multa_detalle' => $this->input->post('multa_detalle'),
				'multa_numrec' => $this->input->post('multa_numrec'),
            );
            
            $multa_id = $this->Multa_model->add_multa($params);
            redirect('multa/index');
        }
        else
        {
			$this->load->model('Reunion_model');
			$data['all_reunion'] = $this->Reunion_model->get_all_reunion();

			$this->load->model('Usuario_model');
			$data['all_usuario'] = $this->Usuario_model->get_all_usuario();
            
            $data['_view'] = 'multa/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a multa
     */
    function edit($multa_id)
    {   
        // check if the multa exists before trying to edit it
        $data['multa'] = $this->Multa_model->get_multa($multa_id);
        
        if(isset($data['multa']['multa_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'reunion_id' => $this->input->post('reunion_id'),
					'usuario_id' => $this->input->post('usuario_id'),
					'multa_monto' => $this->input->post('multa_monto'),
					'multa_fecha' => $this->input->post('multa_fecha'),
					'multa_hora' => $this->input->post('multa_hora'),
					'multa_detalle' => $this->input->post('multa_detalle'),
					'multa_numrec' => $this->input->post('multa_numrec'),
                );

                $this->Multa_model->update_multa($multa_id,$params);            
                redirect('multa/index');
            }
            else
            {
				$this->load->model('Reunion_model');
				$data['all_reunion'] = $this->Reunion_model->get_all_reunion();

				$this->load->model('Usuario_model');
				$data['all_usuario'] = $this->Usuario_model->get_all_usuario();

                $data['_view'] = 'multa/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The multa you are trying to edit does not exist.');
    } 

    /*
     * Deleting multa
     */
    function remove($multa_id)
    {
        $multa = $this->Multa_model->get_multa($multa_id);

        // check if the multa exists before trying to delete it
        if(isset($multa['multa_id']))
        {
            $this->Multa_model->delete_multa($multa_id);
            redirect('multa/index');
        }
        else
            show_error('The multa you are trying to delete does not exist.');
    }
    
}
