<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tipo_integrante extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tipo_integrante_model');
    } 

    /*
     * Listing of tipo_integrante
     */
    function index()
    {
        $data['tipo_integrante'] = $this->Tipo_integrante_model->get_all_tipo_integrante();
        
        $data['_view'] = 'tipo_integrante/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tipo_integrante
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'tipointeg_nombre' => $this->input->post('tipointeg_nombre'),
            );
            
            $tipo_integrante_id = $this->Tipo_integrante_model->add_tipo_integrante($params);
            redirect('tipo_integrante/index');
        }
        else
        {            
            $data['_view'] = 'tipo_integrante/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tipo_integrante
     */
    function edit($tipointeg_id)
    {   
        // check if the tipo_integrante exists before trying to edit it
        $data['tipo_integrante'] = $this->Tipo_integrante_model->get_tipo_integrante($tipointeg_id);
        
        if(isset($data['tipo_integrante']['tipointeg_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'tipointeg_nombre' => $this->input->post('tipointeg_nombre'),
                );

                $this->Tipo_integrante_model->update_tipo_integrante($tipointeg_id,$params);            
                redirect('tipo_integrante/index');
            }
            else
            {
                $data['_view'] = 'tipo_integrante/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tipo_integrante you are trying to edit does not exist.');
    } 

    /*
     * Deleting tipo_integrante
     */
    function remove($tipointeg_id)
    {
        $tipo_integrante = $this->Tipo_integrante_model->get_tipo_integrante($tipointeg_id);

        // check if the tipo_integrante exists before trying to delete it
        if(isset($tipo_integrante['tipointeg_id']))
        {
            $this->Tipo_integrante_model->delete_tipo_integrante($tipointeg_id);
            redirect('tipo_integrante/index');
        }
        else
            show_error('The tipo_integrante you are trying to delete does not exist.');
    }
    
}
