<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Asesor_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get asesor by asesor_id
     */
    function get_asesor($asesor_id)
    {
        $asesor = $this->db->query("
            SELECT
                *

            FROM
                `asesor`

            WHERE
                `asesor_id` = ?
        ",array($asesor_id))->row_array();

        return $asesor;
    }
        
    /*
     * Get all asesor
     */
    function get_all_asesor()
    {
        $asesor = $this->db->query("
            SELECT
                *

            FROM
                `asesor`

            WHERE
                1 = 1

            ORDER BY `asesor_id` DESC
        ")->result_array();

        return $asesor;
    }
        
    /*
     * function to add new asesor
     */
    function add_asesor($params)
    {
        $this->db->insert('asesor',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update asesor
     */
    function update_asesor($asesor_id,$params)
    {
        $this->db->where('asesor_id',$asesor_id);
        return $this->db->update('asesor',$params);
    }
    
    /*
     * function to delete asesor
     */
    function delete_asesor($asesor_id)
    {
        return $this->db->delete('asesor',array('asesor_id'=>$asesor_id));
    }
}
