<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Asesor_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get asesor by asesor_id
     */
    function get_asesor($asesor_id)
    {
        $asesor = $this->db->query("
            SELECT
                *

            FROM
                `asesor`

            WHERE
                `asesor_id` = ?
        ",array($asesor_id))->row_array();

        return $asesor;
    }
        
    /*
     * Get all asesor
     */
    function get_all_asesor()
    {
        $asesor = $this->db->query("
            SELECT
                a.*, e.estado_color, e.estado_descripcion

            FROM
                asesor a
            LEFT JOIN estado e on a.estado_id = e.estado_id
            WHERE
                1 = 1

            ORDER BY `asesor_id` DESC
        ")->result_array();

        return $asesor;
    }
        
    /*
     * function to add new asesor
     */
    function add_asesor($params)
    {
        $this->db->insert('asesor',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update asesor
     */
    function update_asesor($asesor_id,$params)
    {
        $this->db->where('asesor_id',$asesor_id);
        return $this->db->update('asesor',$params);
    }
    
    /*
     * function to delete asesor
     */
    function delete_asesor($asesor_id)
    {
        return $this->db->delete('asesor',array('asesor_id'=>$asesor_id));
    }
    /*
     * Verifica si ya hay un asesor registrado con un nombre y apellido
     */
    function es_asesor_registrado($nombre, $apellido)
    {
        $sql = "SELECT
                      count(a.asesor_id) as resultado
                  FROM
                      asesor a
                 WHERE
                      a.asesor_nombre = '".$nombre."'
                      and a.asesor_apellido = '".$apellido."'";

        $asesor = $this->db->query($sql)->row_array();
        return $asesor['resultado'];
    }
    
     /* Get asesor ..... usuario */
    function get_asesorusuario($usuario_id)
    {
        $asesor = $this->db->query("
            SELECT
                a.asesor_id
            FROM
                asesor a

            WHERE
                a.usuario_id = ?
        ",array($usuario_id))->row_array();

        return $asesor['asesor_id'];
    }
    
}
