<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Asistencia_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get asistencia by aistencia_id
     */
    function get_asistencia($aistencia_id)
    {
        $asistencia = $this->db->query("
            SELECT
                *

            FROM
                `asistencia`

            WHERE
                `aistencia_id` = ?
        ",array($aistencia_id))->row_array();

        return $asistencia;
    }
        
    /*
     * Get all asistencia
     */
    function get_all_asistencia()
    {
        $asistencia = $this->db->query("
            SELECT
                *

            FROM
                `asistencia`

            WHERE
                1 = 1

            ORDER BY `aistencia_id` DESC
        ")->result_array();

        return $asistencia;
    }
        
    /*
     * function to add new asistencia
     */
    function add_asistencia($params)
    {
        $this->db->insert('asistencia',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update asistencia
     */
    function update_asistencia($aistencia_id,$params)
    {
        $this->db->where('aistencia_id',$aistencia_id);
        return $this->db->update('asistencia',$params);
    }
    
    /*
     * function to delete asistencia
     */
    function delete_asistencia($aistencia_id)
    {
        return $this->db->delete('asistencia',array('aistencia_id'=>$aistencia_id));
    }
}
