<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Garante_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get garante by garante_id
     */
    function get_garante($garante_id)
    {
        $garante = $this->db->query("
            SELECT
                *

            FROM
                `garante`

            WHERE
                `garante_id` = ?
        ",array($garante_id))->row_array();

        return $garante;
    }
        
    /*
     * Get all garante
     */
    function get_all_garante()
    {
        $garante = $this->db->query("
            SELECT
                *

            FROM
                `garante`

            WHERE
                1 = 1

            ORDER BY `garante_id` DESC
        ")->result_array();

        return $garante;
    }
        
    /*
     * function to add new garante
     */
    function add_garante($params)
    {
        $this->db->insert('garante',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update garante
     */
    function update_garante($garante_id,$params)
    {
        $this->db->where('garante_id',$garante_id);
        return $this->db->update('garante',$params);
    }
    
    /*
     * function to delete garante
     */
    function delete_garante($garante_id)
    {
        return $this->db->delete('garante',array('garante_id'=>$garante_id));
    }
}
