<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Integrante_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get integrante by integrante_id
     */
    function get_integrante($integrante_id)
    {
        $integrante = $this->db->query("
            SELECT
                *

            FROM
                `integrante`

            WHERE
                `integrante_id` = ?
        ",array($integrante_id))->row_array();

        return $integrante;
    }
        
    /*
     * Get all integrante
     */
    function get_all_integrante()
    {
        $integrante = $this->db->query("
            SELECT
                *

            FROM
                `integrante`

            WHERE
                1 = 1

            ORDER BY `integrante_id` DESC
        ")->result_array();

        return $integrante;
    }
        
    /*
     * function to add new integrante
     */
    function add_integrante($params)
    {
        $this->db->insert('integrante',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update integrante
     */
    function update_integrante($integrante_id,$params)
    {
        $this->db->where('integrante_id',$integrante_id);
        return $this->db->update('integrante',$params);
    }
    
    /*
     * function to delete integrante
     */
    function delete_integrante($integrante_id)
    {
        return $this->db->delete('integrante',array('integrante_id'=>$integrante_id));
    }
}
