<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Integrante_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get integrante by integrante_id
     */
    function get_integrante($integrante_id)
    {
        $integrante = $this->db->query("
            SELECT
                *

            FROM
                `integrante`

            WHERE
                `integrante_id` = ?
        ",array($integrante_id))->row_array();

        return $integrante;
    }
        
    /*
     * Get all integrante
     */
    function get_all_integrante()
    {
        $integrante = $this->db->query("
            SELECT
                *

            FROM
                `integrante`

            WHERE
                1 = 1

            ORDER BY `integrante_id` ASC
        ")->result_array();

        return $integrante;
    }
        
    /*
     * function to add new integrante
     */
    function add_integrante($params)
    {
        $this->db->insert('integrante',$params);
        return $this->db->insert_id();
    }

    function add_deuda($params)
    {
        $this->db->insert('deuda_institucion',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update integrante
     */
    function update_integrante($integrante_id,$params)
    {
        $this->db->where('integrante_id',$integrante_id);
        return $this->db->update('integrante',$params);
    }
    
    /*
     * function to delete integrante
     */
    function delete_integrante($integrante_id)
    {
        return $this->db->delete('integrante',array('integrante_id'=>$integrante_id));
    }
    
    /* Get # de Integrantes de un grupo */
    function get_numintegrantes_grupo($grupo_id)
    {
        $integrante = $this->db->query("
            SELECT
                count(i.integrante_id) as resultado

            FROM
                integrante i

            WHERE
                i.grupo_id = ?
        ",array($grupo_id))->row_array();

        return $integrante['resultado'];
    }
    
    /* existe integrante en este grupo? */
    function get_existeintegrante($grupo_id, $cliente_id)
    {
        $existe = $this->db->query("
            SELECT
                count(i.integrante_id) as resultado

            FROM
                integrante i

            WHERE
                i.grupo_id = $grupo_id
                and cliente_id = $cliente_id
        ")->row_array();

        return $existe['resultado'];
    }

    function get_monto_maximo($cliente_id)
    {
        $total = $this->db->query("
            SELECT
                cliente_montomax as resul

            FROM
                cliente 

            WHERE
                cliente_id = ".$cliente_id."
        ")->row_array();

        return $total['resul'];
    }
    
    /* catidad de dinero solicitado por integrantes de un grupo */
    function get_montototal_grupo($grupo_id)
    {
        $total = $this->db->query("
            SELECT
                sum(i.integrante_montosolicitado) as resultado

            FROM
                integrante i

            WHERE
                i.grupo_id = $grupo_id
        ")->row_array();

        return $total['resultado'];
    }
    
    function get_alldeudas($integrante_id)
    {
        $deuda = $this->db->query("
            SELECT
                d.*, i.integrante_id, c.cliente_id

            FROM
                deuda_institucion d, integrante i, cliente c

            WHERE
                d.cliente_id=c.cliente_id
                and  c.cliente_id = i.cliente_id
                and  i.integrante_id = ".$integrante_id."

        ")->result_array();

        return $deuda;
    }
    
    /* Get integrante by integrante_id */
    function get_integrante_cliente($cliente_id)
    {
        $integrante = $this->db->query("
            SELECT
                i.integrante_id

            FROM
                integrante i

            WHERE
                `cliente_id` = ?
        ",array($cliente_id))->row_array();

        return $integrante['integrante_id'];
    }
    
}
