<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Multa_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get multa by multa_id
     */
    function get_multa($multa_id)
    {
        $multa = $this->db->query("
            SELECT
                *

            FROM
                `multa`

            WHERE
                `multa_id` = ?
        ",array($multa_id))->row_array();

        return $multa;
    }
        
    /*
     * Get all multa
     */
    function get_all_multa()
    {
        $multa = $this->db->query("
            SELECT
                *

            FROM
                `multa`

            WHERE
                1 = 1

            ORDER BY `multa_id` DESC
        ")->result_array();

        return $multa;
    }
        
    /*
     * function to add new multa
     */
    function add_multa($params)
    {
        $this->db->insert('multa',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update multa
     */
    function update_multa($multa_id,$params)
    {
        $this->db->where('multa_id',$multa_id);
        return $this->db->update('multa',$params);
    }
    
    /*
     * function to delete multa
     */
    function delete_multa($multa_id)
    {
        return $this->db->delete('multa',array('multa_id'=>$multa_id));
    }
}
