<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Reunion_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get reunion by reunion_id
     */
    function get_reunion($reunion_id)
    {
        $reunion = $this->db->query("
            SELECT
                *

            FROM
                `reunion`

            WHERE
                `reunion_id` = ?
        ",array($reunion_id))->row_array();

        return $reunion;
    }
        
    /*
     * Get all reunion
     */
    function get_all_reunion()
    {
        $reunion = $this->db->query("
            SELECT
                r.*, g.*

            FROM
                reunion r, grupo g

            WHERE
                r.grupo_id=g.grupo_id

            ORDER BY `reunion_id` DESC
        ")->result_array();

        return $reunion;
    }
        
    /*
     * function to add new reunion
     */
    function add_reunion($params)
    {
        $this->db->insert('reunion',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update reunion
     */
    function update_reunion($reunion_id,$params)
    {
        $this->db->where('reunion_id',$reunion_id);
        return $this->db->update('reunion',$params);
    }
    
    /*
     * function to delete reunion
     */
    function delete_reunion($reunion_id)
    {
        return $this->db->delete('reunion',array('reunion_id'=>$reunion_id));
    }
}
