<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Reunion_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get reunion by reunion_id
     */
    function get_reunion($reunion_id)
    {
        $reunion = $this->db->query("
            SELECT
                *

            FROM
                `reunion`

            WHERE
                `reunion_id` = ?
        ",array($reunion_id))->row_array();

        return $reunion;
    }
        
    /*
     * Get all reunion
     */
    function get_all_reunion()
    {
        $reunion = $this->db->query("
            SELECT
                r.*, g.*

            FROM
                reunion r, grupo g

            WHERE
                r.grupo_id=g.grupo_id

            ORDER BY `reunion_id` DESC
        ")->result_array();

        return $reunion;
    }
        
    /*
     * function to add new reunion
     */
    function add_reunion($params)
    {
        $this->db->insert('reunion',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update reunion
     */
    function update_reunion($reunion_id,$params)
    {
        $this->db->where('reunion_id',$reunion_id);
        return $this->db->update('reunion',$params);
    }
    
    /*
     * function to delete reunion
     */
    function delete_reunion($reunion_id)
    {
        return $this->db->delete('reunion',array('reunion_id'=>$reunion_id));
    }
    /*
     * Get Integrantes-clientes degrupo que pertenece a una reunion
     */
    function get_idintegrantes($reunion_id)
    {
        $reunion = $this->db->query("
            SELECT
                i.integrante_id
            FROM
                integrante i
            LEFT JOIN grupo g on i.grupo_id = g.grupo_id
            LEFT JOIN reunion r on r.grupo_id = g.grupo_id
            WHERE
                r.reunion_id = $reunion_id
        ")->result_array();

        return $reunion;
    }
    /*
     * Get Integrantes-clientes degrupo que pertenece a una reunion
     */
    function registrado_ya_asistencia($reunion_id, $integrante_id)
    {
        $reunion = $this->db->query("
            SELECT
                a.integrante_id
            FROM
                asistencia a
            WHERE
                a.reunion_id = $reunion_id
                and a.integrante_id = $integrante_id
        ")->result_array();

        return $reunion;
    }
    /*
     * Get reunion, grupo para asistencia 
     */
    function get_this_reunion($reunion_id)
    {
        $reunion = $this->db->query("
            SELECT
                r.*, g.grupo_nombre, concat (a.asesor_nombre, ' ', a.asesor_apellido) as elasesor,
                g.grupo_tiempotolerancia, g.grupo_monto
            FROM
                reunion r
            LEFT JOIN grupo g on r.grupo_id = g.grupo_id
            LEFT JOIN asesor a on g.asesor_id = a.asesor_id
            WHERE
                r.reunion_id = $reunion_id
        ")->row_array();

        return $reunion;
    }
    /*
     * Get integrantes 
     */
    function get_this_clientesgrupo($reunion_id, $grupo_id, $reunion_numero)
    {
        $cliente = $this->db->query("
            SELECT
                c.cliente_id, concat(c.cliente_nombre, ' ', c.cliente_apellido) as elcliente,
                c.cliente_ci, c.cliente_extencionci, c.cliente_telefono, c.cliente_celular,
                cr.credito_id, cu.cuota_id, cu.cuota_monto, a.asistencia_registro,a.asistencia_pagado,
                a.asistencia_retraso, a.asistencia_falta, a.asistencia_observacion, i.integrante_id,
                a.asistencia_recibor, a.asistencia_recibof, a.asistencia_ahorro, i.integrante_montosolicitado,
                g.grupo_multaenvio
            FROM
                integrante i
            LEFT JOIN cliente c on i.cliente_id = c.cliente_id
            LEFT JOIN credito cr on c.cliente_id = cr.cliente_id
            LEFT JOIN cuota cu on cr.credito_id = cu.credito_id
            LEFT JOIN asistencia a on i.integrante_id = a.integrante_id
            LEFT JOIN grupo g on i.grupo_id = g.grupo_id
            LEFT JOIN reunion r on g.grupo_id = r.grupo_id
            WHERE
                i.grupo_id = $grupo_id
                and a.reunion_id = r.reunion_id
                and r.reunion_id = $reunion_id
                and r.reunion_numero = $reunion_numero
                and cu.cuota_numero  = $reunion_numero
        ")->result_array();

        return $cliente;
    }
    
}
