<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tipo_integrante_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tipo_integrante by tipointeg_id
     */
    function get_tipo_integrante($tipointeg_id)
    {
        $tipo_integrante = $this->db->query("
            SELECT
                *

            FROM
                `tipo_integrante`

            WHERE
                `tipointeg_id` = ?
        ",array($tipointeg_id))->row_array();

        return $tipo_integrante;
    }
        
    /*
     * Get all tipo_integrante
     */
    function get_all_tipo_integrante()
    {
        $tipo_integrante = $this->db->query("
            SELECT
                *

            FROM
                `tipo_integrante`

            WHERE
                1 = 1

            ORDER BY `tipointeg_id` DESC
        ")->result_array();

        return $tipo_integrante;
    }
        
    /*
     * function to add new tipo_integrante
     */
    function add_tipo_integrante($params)
    {
        $this->db->insert('tipo_integrante',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tipo_integrante
     */
    function update_tipo_integrante($tipointeg_id,$params)
    {
        $this->db->where('tipointeg_id',$tipointeg_id);
        return $this->db->update('tipo_integrante',$params);
    }
    
    /*
     * function to delete tipo_integrante
     */
    function delete_tipo_integrante($tipointeg_id)
    {
        return $this->db->delete('tipo_integrante',array('tipointeg_id'=>$tipointeg_id));
    }
}
