<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tipo_credito_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tipo_credito by tipocredito_id
     */
    function get_tipo_credito($tipocredito_id)
    {
        $tipo_credito = $this->db->query("
            SELECT
                *

            FROM
                `tipo_credito`

            WHERE
                `tipocredito_id` = ?
        ",array($tipocredito_id))->row_array();

        return $tipo_credito;
    }
        
    /*
     * Get all tipo_credito
     */
    function get_all_tipo_credito()
    {
        $tipo_credito = $this->db->query("
            SELECT
                *

            FROM
                `tipo_credito`

            WHERE
                1 = 1

            ORDER BY `tipocredito_id` DESC
        ")->result_array();

        return $tipo_credito;
    }
        
    /*
     * function to add new tipo_credito
     */
    function add_tipo_credito($params)
    {
        $this->db->insert('tipo_credito',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tipo_credito
     */
    function update_tipo_credito($tipocredito_id,$params)
    {
        $this->db->where('tipocredito_id',$tipocredito_id);
        return $this->db->update('tipo_credito',$params);
    }
    
    /*
     * function to delete tipo_credito
     */
    function delete_tipo_credito($tipocredito_id)
    {
        return $this->db->delete('tipo_credito',array('tipocredito_id'=>$tipocredito_id));
    }
}
