<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tipo_garantia_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tipo_garantia by tipogarant_id
     */
    function get_tipo_garantia($tipogarant_id)
    {
        $tipo_garantia = $this->db->query("
            SELECT
                *

            FROM
                `tipo_garantia`

            WHERE
                `tipogarant_id` = ?
        ",array($tipogarant_id))->row_array();

        return $tipo_garantia;
    }
        
    /*
     * Get all tipo_garantia
     */
    function get_all_tipo_garantia()
    {
        $tipo_garantia = $this->db->query("
            SELECT
                *

            FROM
                `tipo_garantia`

            WHERE
                1 = 1

            ORDER BY `tipogarant_id` DESC
        ")->result_array();

        return $tipo_garantia;
    }
        
    /*
     * function to add new tipo_garantia
     */
    function add_tipo_garantia($params)
    {
        $this->db->insert('tipo_garantia',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tipo_garantia
     */
    function update_tipo_garantia($tipogarant_id,$params)
    {
        $this->db->where('tipogarant_id',$tipogarant_id);
        return $this->db->update('tipo_garantia',$params);
    }
    
    /*
     * function to delete tipo_garantia
     */
    function delete_tipo_garantia($tipogarant_id)
    {
        return $this->db->delete('tipo_garantia',array('tipogarant_id'=>$tipogarant_id));
    }
}
